---
###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: Lint Code Base

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all pull requests #
#############################
on:
  pull_request:

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2

      ##########################
      # Github Super Linter needs
      # the latest definitions installed
      ##########################
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16.x
      - run: npm install

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: docker://ghcr.io/github/super-linter:slim-v4
        env:
          # All Environment variables are defined here https://github.com/github/super-linter#environment-variables
          # The name of the repository default branch.
          DEFAULT_BRANCH: main
          # Directory for all linter configuration rules. We symlink our root .eslintrc.js to this directory
          LINTER_RULES_PATH: /
          VALIDATE_ALL_CODEBASE: true
          TYPESCRIPT_ES_CONFIG_FILE: .eslintrc.js
          VALIDATE_TERRAFORM: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_MD: true
          VALIDATE_TYPESCRIPT_ES: true
          VALIDATE_YAML: true
