# Delete this when you generate a repository from this template
name: Build Infrastructure

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./.aws
    steps:
      - uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # tag=v2
      - uses: hashicorp/setup-terraform@3d8debd658c92063839bc97da5c2427100420dec # renovate: tag=v1.3.2
        with:
          terraform_version: 0.13.5
          terraform_wrapper: false
      - uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # renovate: tag=v2.5.1
        with:
          node-version: '16.x'
      - run: npm ci
        working-directory: ${{env.working-directory}}
      - run: npm run build:dev
        working-directory: ${{env.working-directory}}
